### ISSUE TITLE
Growthcraft Cellar

### ISSUE THREAD

**Issue by Alatyami** [GrowthcraftCE/Growthcraft-1.16#2]
# Growthcraft Cellar

## Growthcraft Cellar Devices

- [ ] Brew Kettle
- [ ] Brew Kettle Lid
- [ ] Fermentation Barrel 
- [ ] Culture Jar
- [ ] Fruit Press

## Growthcraft Cellar Trees

- [ ] Cork Wood (Log)
- [ ] Cork Wood (Stripped Log) 
- [ ] Cork Tree Sapling
- [ ] Cork Tree Leaves
- [ ] Cork Tree Bark

## Yeast
    
- [ ] Brewer’s Yeast
- [ ] Lager Yeast
- [ ] Bayanus Yeast
- [ ] Ethereal Yeast 
- [ ] Origin Yeast
